# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT
---
# https://docs.github.com/actions/learn-github-actions
name: daily
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

permissions: {}

env:
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  CW_MAP: '1'
  CW_JOBS: '5'
  CW_CURL_TEST: '1'
  CW_PKG_SIGN: '1'
  CW_PKG_NODELETE: '1'
  CW_PKG_FLATTEN: '1'
  DO_NOT_TRACK: '1'
  SIGN_PKG_KEY_ID: 'BDCF067D3908B2727A4A948767C1003740BF8DC2'

jobs:
  win:
    name: 'Windows x64'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: '300'
      - name: 'build'
        env:
          COSIGN_PKG_GPG_PASS: '${{ secrets.COSIGN_PKG_GPG_PASS }}'
          COSIGN_PKG_KEY_PASS: '${{ secrets.COSIGN_PKG_KEY_PASS }}'
          SIGN_PKG_GPG_PASS: '${{ secrets.SIGN_PKG_GPG_PASS }}'
          SIGN_PKG_KEY_PASS: '${{ secrets.SIGN_PKG_KEY_PASS }}'
          CW_LLVM_MINGW_DL: '1'
          CW_LLVM_MINGW_ONLY: '1'
        run: |
          export CW_CONFIG='werror-dev-win'
          export CW_REVISION="$(TZ=UTC date +'%Y%m%d')"
          . ./_versions.sh
          sudo podman image trust set --type reject default
          sudo podman image trust set --type accept docker.io/library
          time podman pull "${OCI_IMAGE_DEBIAN_TESTING}"
          podman images --digests
          time podman run --volume "$(pwd):$(pwd)" --workdir "$(pwd)" \
            --env-file <(env | grep -a -E \
              '^(CW_|SIGN_|COSIGN_|GITHUB_|DO_NOT_TRACK)') \
            "${OCI_IMAGE_DEBIAN_TESTING}" \
            sh -c ./_ci-linux-debian.sh

      - name: 'list dependencies'
        run: cat urls.txt ./*-version-*.txt || true
      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: 'curl-windows-daily'
          retention-days: 42
          path: |
            *-*-mingw*.*
            urls.txt
